require "./libghostty/link"

require "./libghostty/types"
require "./libghostty/allocator"
require "./libghostty/io"
require "./libghostty/device"
require "./libghostty/color"
require "./libghostty/color_scheme"
require "./libghostty/sgr"
require "./libghostty/modes"
require "./libghostty/point"
require "./libghostty/style"
require "./libghostty/screen"
require "./libghostty/grid_ref"
require "./libghostty/size_report"
require "./libghostty/build_info"
require "./libghostty/selection"
require "./libghostty/terminal"
require "./libghostty/render"
require "./libghostty/grid_ref_tracked"
require "./libghostty/formatter"
require "./libghostty/key"
require "./libghostty/mouse"
require "./libghostty/search"
require "./libghostty/snapshot"
require "./libghostty/sys"
require "./libghostty/osc"
require "./libghostty/focus"
require "./libghostty/unicode"
require "./libghostty/paste"
require "./libghostty/kitty_graphics"

module TermBuf::Spec
  # Raw bindings to libghostty-vt, the terminal emulator extracted from
  # Ghostty.
  #
  # `LibGhosttyVt` is a faithful mirror of the C headers and nothing more: the
  # names, the layouts and the argument order are all as the library declares
  # them, and no attempt is made here to make any of it pleasant. The harness
  # built on top is where the pleasantness goes.
  #
  # Two things do live here, because they exist to stop a caller getting the C
  # contract wrong rather than to hide it. `DEFAULT_ALLOCATOR` names the null
  # pointer that every allocator argument accepts, and `.sized` fills in the
  # `size` field that the versioned structs require.
  #
  # `link.cr`, required first, is generated by `scripts/build-libghostty-vt.sh`
  # and carries the `@[Link]` annotation. Every file here reopens
  # `lib LibGhosttyVt` without an annotation of its own.
  #
  # ## One mistake to know about before editing these bindings
  #
  # A Crystal value type handed back by a getter is a copy, and three separate
  # bugs in this layer were that same fact wearing different clothes:
  #
  # * `options.extra.screen = ...` sets the field on a copy of `extra` and
  #   throws it away, so the formatter saw a zero size and quietly emitted
  #   none of the extras that were asked for. `.formatter_terminal_options`
  #   below exists to keep anyone from writing it.
  # * `mask.value.bits[word] |= bit` mutates a copy of the static array, so
  #   the mask stayed empty and every read of it answered false.
  # * A `type` alias to a function signature, used as a struct field, is
  #   stored as a two word `Proc` rather than C's single function pointer,
  #   which made `GhosttyReader` and `GhosttyWriter` eight bytes too long and
  #   put `userdata` where the library was not looking for it. Struct fields
  #   spell their function type out inline for that reason; see `io.cr`.
  #
  # None of the three fails to compile, none is visible at the call site, and
  # each needed something to actually run before it showed itself. That is
  # what `spec/libghostty_spec.cr` is for: it asserts every layout against
  # `ghostty_type_json`, the library's own ABI manifest, and calls each area
  # once. Reach for a pointer, or for the helpers here, rather than for the
  # obvious idiom.
  module LibGhostty
    # The allocator argument to pass when the default allocator will do, which
    # is nearly always. libghostty-vt reads a null allocator pointer as "use
    # libc's malloc and free", and there is no reason for a test harness to
    # want anything else.
    DEFAULT_ALLOCATOR = Pointer(LibGhosttyVt::Allocator).null

    # Returns a zeroed struct with its `size` field filled in, which is what
    # the C `GHOSTTY_INIT_SIZED` macro does.
    #
    # Several structs in the API carry their own size as their first field, so
    # that the library can tell which version of the layout the caller was
    # compiled against. Leaving it zero is not a small mistake: the library
    # concludes the caller knows about none of the fields.
    #
    #     options = LibGhostty.sized(LibGhosttyVt::FormatterTerminalOptions)
    #     options.emit = LibGhosttyVt::FormatterFormat::Plain
    def self.sized(type : T.class) : T forall T
      value = T.new
      value.size = LibC::SizeT.new(sizeof(T))
      value
    end

    # Returns formatter options with the `size` field of the options and of
    # both nested extras filled in.
    #
    # The nested `extra` and `extra.screen` structs are sized separately from
    # the one that contains them, so `.sized` alone is not enough here and a
    # caller that forgets ends up with a formatter that quietly ignores every
    # extra it asked for.
    def self.formatter_terminal_options : LibGhosttyVt::FormatterTerminalOptions
      extra = sized(LibGhosttyVt::FormatterTerminalExtra)
      extra.screen = sized(LibGhosttyVt::FormatterScreenExtra)

      options = sized(LibGhosttyVt::FormatterTerminalOptions)
      options.extra = extra
      options
    end
  end
end
