#!/usr/bin/env bash
# Build libghostty-vt and write the Crystal link stub that points at it.
# Run by `shards install` as a postinstall script, and by `make lib`.
#
# The build happens once. Afterwards the only things left on disk are the built
# library and its headers, which come to about 13MB. The ghostty source is
# fetched into a temporary directory and deleted when the build finishes.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
pin="$root/vendor/ghostty.pin"
out="$root/vendor/build"
work="$root/vendor/.source"
gen="$root/src/termbuf-spec/libghostty/link.cr"
stamp="$out/.built-from"

# The shared library is linked rather than the static one. Zig bundles its own
# compiler_rt into the archive. Its 128-bit helpers collide with the ones the
# Crystal runtime carries. Dropping that member does not help, because the
# archive then loses the long double conversions that Crystal does not provide.
# A shared library keeps both of those internal. It exports only the ghostty_*
# symbols.
case "$(uname -s)" in
  Darwin) lib="$out/lib/libghostty-vt.dylib" ;;
  *)      lib="$out/lib/libghostty-vt.so" ;;
esac

MIN_ZIG="0.16.0"

die() { printf 'build-libghostty-vt: %s\n' "$*" >&2; exit 1; }
log() { printf 'build-libghostty-vt: %s\n' "$*" >&2; }

# Reads one `key = value` line out of the pin file.
pinned() {
  sed -n "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*//p" "$pin" | head -1
}

[ -f "$pin" ] || die "$pin is missing"

url="$(pinned url)"
commit="$(pinned commit)"

[ -n "$url" ] || die "$pin does not name a url"
[ -n "$commit" ] || die "$pin does not name a commit"

# Writes the link stub. Crystal needs a string literal in the Link annotation.
# It does not expand __DIR__ inside one, and a `lib` declaration cannot be
# written inside a macro, so the absolute paths are written out here. The
# binding files reopen this lib and add their fun declarations to it.
write_link_stub() {
  mkdir -p "$(dirname "$gen")"
  cat > "$gen" <<EOF
# Generated by scripts/build-libghostty-vt.sh. Do not edit.
#
# Built from ghostty $commit with zig $1.

@[Link(ldflags: "-L$out/lib -lghostty-vt -Wl,-rpath,$out/lib")]
lib LibGhosttyVt
end
EOF
  log "wrote ${gen#"$root/"}"
}

# Nothing to do when the library on disk was built from the pinned commit.
# This is the usual case. The build runs once, and every run after it stops
# here without fetching anything.
if [ -f "$lib" ] && [ -f "$stamp" ] && [ "$(sed -n '1p' "$stamp")" = "$commit" ]; then
  log "libghostty-vt is up to date ($commit)"
  write_link_stub "$(sed -n '2p' "$stamp")"
  exit 0
fi

command -v git >/dev/null 2>&1 || die "git is required and was not found in PATH"
command -v zig >/dev/null 2>&1 || die "zig $MIN_ZIG or newer is required and was not found in PATH"

zig_version="$(zig version)"
lowest="$(printf '%s\n%s\n' "$MIN_ZIG" "$zig_version" | sort -V | head -1)"
[ "$lowest" = "$MIN_ZIG" ] || die "zig $zig_version is older than the required $MIN_ZIG"

# The source and zig's two caches come to about 550MB. None of it is read
# again once the library is built. All of it goes under one directory, which
# is removed on the way out whether the build worked or not.
cleanup() { rm -rf "$work"; }
trap cleanup EXIT

rm -rf "$work"
mkdir -p "$work/src"

# Fetch the one pinned commit by its hash. A fetch by hash is self checking,
# because git verifies what arrives against the hash that was asked for.
log "fetching ghostty $commit"
git -C "$work/src" init --quiet
git -C "$work/src" remote add origin "$url"
git -C "$work/src" fetch --quiet --depth 1 origin "$commit" ||
  die "could not fetch $commit from $url"
git -C "$work/src" checkout --quiet --detach FETCH_HEAD

[ -f "$work/src/build.zig" ] || die "ghostty $commit has no build.zig"

log "building libghostty-vt with zig $zig_version"
(
  cd "$work/src"
  zig build \
    -Demit-lib-vt=true \
    -Demit-xcframework=false \
    -Doptimize=ReleaseFast \
    --prefix "$out" \
    --cache-dir "$work/cache" \
    --global-cache-dir "$work/global-cache"
)

[ -f "$lib" ] || die "build finished but $lib was not produced"

# Which commit this was built from, and which zig built it. The first line is
# what the check at the top compares against.
printf '%s\n%s\n' "$commit" "$zig_version" > "$stamp"

write_link_stub "$zig_version"
