#!/usr/bin/env bash
# Build the vendored libghostty-vt static library and generate the Crystal
# link stub that points at it. Run by `shards install` (postinstall) and by
# `make lib`. Safe to run repeatedly: it does nothing when the artifacts are
# already newer than the vendored source.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="$root/vendor/ghostty"
out="$root/vendor/build"
gen="$root/src/termbuf-spec/libghostty/link.cr"

# The shared library rather than the static one, deliberately. Zig bundles its
# own compiler_rt into the archive, and linking that beside the Crystal runtime
# is a pile of duplicate symbol errors for the 128-bit helpers they both carry.
# Dropping the member is not an option either: the archive also needs the
# long double conversions, which Crystal does not provide. A shared library
# keeps all of that internal and exports only the 204 ghostty_* symbols.
case "$(uname -s)" in
  Darwin) lib="$out/lib/libghostty-vt.dylib" ;;
  *)      lib="$out/lib/libghostty-vt.so" ;;
esac

MIN_ZIG="0.16.0"

die() { printf 'build-libghostty-vt: %s\n' "$*" >&2; exit 1; }
log() { printf 'build-libghostty-vt: %s\n' "$*" >&2; }

# The submodule is not fetched when this shard is installed as a dependency,
# so fetch it here rather than assuming a recursive clone.
if [ ! -f "$src/build.zig" ]; then
  [ -d "$root/.git" ] || die "vendor/ghostty is missing and this is not a git checkout"
  log "fetching vendor/ghostty submodule"
  git -C "$root" submodule update --init vendor/ghostty
fi

command -v zig >/dev/null 2>&1 || die "zig $MIN_ZIG or newer is required and was not found in PATH"

zig_version="$(zig version)"
lowest="$(printf '%s\n%s\n' "$MIN_ZIG" "$zig_version" | sort -V | head -1)"
[ "$lowest" = "$MIN_ZIG" ] || die "zig $zig_version is older than the required $MIN_ZIG"

head_commit="$(git -C "$src" rev-parse HEAD 2>/dev/null || echo unknown)"
stamp="$out/.built-from"

if [ -f "$lib" ] && [ -f "$stamp" ] && [ "$(cat "$stamp")" = "$head_commit" ]; then
  log "libghostty-vt is up to date ($head_commit)"
else
  log "building libghostty-vt from $head_commit with zig $zig_version"
  (
    cd "$src"
    zig build \
      -Demit-lib-vt=true \
      -Demit-xcframework=false \
      -Doptimize=ReleaseFast \
      --prefix "$out"
  )
  [ -f "$lib" ] || die "build finished but $lib was not produced"
  printf '%s\n' "$head_commit" > "$stamp"
fi

# The Link annotation needs a string literal, and Crystal does not expand
# __DIR__ inside one, so the absolute paths are written out here. The bindings
# reopen this lib with their fun declarations.
mkdir -p "$(dirname "$gen")"
cat > "$gen" <<EOF
# Generated by scripts/build-libghostty-vt.sh. Do not edit.
#
# Built from ghostty $head_commit with zig $zig_version.

@[Link(ldflags: "-L$out/lib -lghostty-vt -Wl,-rpath,$out/lib")]
lib LibGhosttyVt
end
EOF

log "wrote ${gen#"$root/"}"
